Repository NUbots/NUbots, pull requests merged in 2021-05, with the labels that each got.

#457 Fix Keyboardwalk Eigen Error
  shared/utility/motion/InverseKinematics.cpp
Labels: bug

#452 Updates CM740 Sensor Conversion
  module/platform/darwin/HardwareIO/src/Convert.hpp
Labels: bug, documentation

#451 Fixes Field.proto message comment
  shared/message/localisation/Field.proto
Labels: documentation

#96 KickPlanner now uses game state as a factor for determining a kick
  module/behaviour/planning/KickPlanner/src/KickPlanner.cpp
  module/behaviour/planning/KickPlanner/src/KickPlanner.hpp
Labels: enhancement

#447 Adds NUsight's dependencies to the dockerfile
  docker/Dockerfile
Labels: NUsight2, dependencies, javascript

#448 Updates build badges post NUsight2 CI fix
  README.md
Labels: NUsight2, enhancement

#394 Add communication to connect to the Webots Robocup controller.
  module/platform/Webots/CMakeLists.txt
  module/platform/Webots/README.md
  module/platform/Webots/data/config/webots.yaml
  module/platform/Webots/src/Webots.cpp
  module/platform/Webots/src/Webots.hpp
  module/platform/Webots/tests/Webots.cpp
  roles/webots.role
  roles/webots_keyboard.role
  shared/clock/clock.cpp
  shared/message/platform/webots/ConnectRequest.proto
  shared/message/platform/webots/messages.proto
Labels: enhancement, help wanted, high priority, robocup

#350 Fix the mutex inside FileWatcher to make it reentrant + Fix unit test.
  module/extension/FileWatcher/src/FileWatcher.cpp
  module/extension/FileWatcher/src/FileWatcher.hpp
  module/extension/FileWatcher/tests/FileWatcherTestDirectory.cpp
  module/extension/FileWatcher/tests/FileWatcherTestFile.cpp
  shared/extension/FileWatch.hpp
Labels: bug, enhancement

#449 Changes `./b target` default behaviour to pull from dockerhub
  tools/target.py
  tools/utility/dockerise/platform.py
Labels: enhancement

#486 Make b format flag to skip nusight
  tools/format.py
Labels: enhancement
