Repository NUbots/NUbots, pull requests merged in 2021-06, with the labels that each got.

#383 Make setting the log level from a file neater.
  module/input/ImageDecompressor/src/ImageDecompressor.cpp
  module/output/ImageCompressor/src/ImageCompressor.cpp
  module/platform/Webots/src/Webots.cpp
  module/support/LocalisationSimulator/src/LocalisationSimulator.cpp
  shared/extension/Configuration.hpp
  shared/utility/support/yaml_log_level.hpp
  tools/module/generate.py
Labels: enhancement

#513 Changes return types of walk engine functions which mutated many references
  module/motion/QuinticWalk/src/QuinticWalk.cpp
  module/motion/QuinticWalk/src/WalkEngine.cpp
  module/motion/QuinticWalk/src/WalkEngine.hpp
  shared/utility/motion/splines/TrajectoryUtils.hpp
Labels: bug

#516 Nicer C++ stuff for motion metamodule/utils
  module/motion/QuinticWalk/src/QuinticWalk.cpp
  module/motion/QuinticWalk/src/QuinticWalk.hpp
  module/motion/QuinticWalk/src/WalkEngine.cpp
  module/motion/QuinticWalk/src/WalkEngine.hpp
  shared/utility/motion/ForwardKinematics.hpp
  shared/utility/motion/InverseKinematics.cpp
  shared/utility/motion/InverseKinematics.hpp
  shared/utility/motion/splines/Combination.hpp
  shared/utility/motion/splines/Footstep.cpp
  shared/utility/motion/splines/Footstep.hpp
  shared/utility/motion/splines/Polynom.hpp
  shared/utility/motion/splines/SmoothSpline.hpp
  shared/utility/motion/splines/Spline.hpp
  shared/utility/motion/splines/SplineContainer.hpp
  shared/utility/motion/splines/TrajectoryUtils.hpp
Labels: enhancement

#415 Replace the C++ side of NUsight with a generic message forwarding module
  module/output/NetworkForwarder/CMakeLists.txt
  module/output/NetworkForwarder/README.md
  module/output/NetworkForwarder/data/config/NetworkForwarder.yaml
  module/output/NetworkForwarder/src/NetworkForwarder.cpp
  module/output/NetworkForwarder/src/NetworkForwarder.hpp
  module/output/NetworkForwarder/src/generate_handles.py
  module/output/NetworkForwarder/tests/NetworkForwarder.cpp
  module/support/NUsight/CMakeLists.txt
  module/support/NUsight/LICENSE.md
  module/support/NUsight/README.md
  module/support/NUsight/data/config/NUsight.yaml
  module/support/NUsight/report/NUsight.tex
  module/support/NUsight/src/Configuration.cpp
  module/support/NUsight/src/DataPoints.cpp
  module/support/NUsight/src/GameController.cpp
  module/support/NUsight/src/Localisation.cpp
  module/support/NUsight/src/NUsight.cpp
  module/support/NUsight/src/NUsight.hpp
  module/support/NUsight/src/Overview.cpp
  module/support/NUsight/src/ReactionStatistics.cpp
  module/support/NUsight/src/Subsumption.cpp
  module/support/NUsight/src/Vision.cpp
  module/support/NUsight/tests/NUsight.cpp
  roles/balllocalisation.role
  roles/cameratest.role
  roles/filter_playback.role
  roles/gamecontrollertest.role
  roles/gazebo.role
  roles/headbehtest.role
  roles/keyboardwalk.role
  roles/keyboardwalkfake.role
  roles/localisationtest.role
  roles/lookatball.role
  roles/lookatgoal.role
  roles/natnet.role
  roles/nusighttest.role
  roles/playback.role
  roles/ps3walk.role
  roles/robocup.role
  roles/scriptrunner.role
  roles/scripttuner.role
  roles/scripttunerwebots.role
  roles/sensortest.role
  roles/visualmesh.role
  roles/visualmesh_fake.role
  roles/webotsrobocup.role
Labels: NUsight2, enhancement

#416 Add an overview module to replace the functionality removed from the NUsight module
  module/output/Overview/CMakeLists.txt
  module/output/Overview/README.md
  module/output/Overview/data/config/Overview.yaml
  module/output/Overview/src/Overview.cpp
  module/output/Overview/src/Overview.hpp
  module/output/Overview/tests/Overview.cpp
  roles/balllocalisation.role
  roles/cameratest.role
  roles/filter_playback.role
  roles/gamecontrollertest.role
  roles/gazebo.role
  roles/headbehtest.role
  roles/keyboardwalk.role
  roles/keyboardwalkfake.role
  roles/localisationtest.role
  roles/lookatball.role
  roles/lookatgoal.role
  roles/nusighttest.role
  roles/playback.role
  roles/ps3walk.role
  roles/robocup.role
  roles/scriptrunner.role
  roles/scripttuner.role
  roles/sensortest.role
  roles/visualmesh.role
Labels: NUsight2, enhancement

#528 Fix eigen quaternion coeffs problems
  module/input/SensorFilter/src/MotionModel.hpp
  module/motion/QuinticWalk/src/QuinticWalk.cpp
Labels: bug, high priority, robocup

#467 Some more clang tidy "fixes"
  module/behaviour/strategy/PS3Walk/src/Joystick.cpp
  module/behaviour/strategy/PS3Walk/src/Joystick.hpp
  shared/clock/clock.hpp
  shared/utility/file/fileutil.cpp
  shared/utility/input/LimbID.cpp
  shared/utility/input/LimbID.hpp
  shared/utility/input/ServoID.cpp
  shared/utility/input/ServoID.hpp
  shared/utility/io/uart.cpp
  shared/utility/io/uart.hpp
  shared/utility/math/angle.hpp
  shared/utility/nusight/NUhelpers.hpp
  shared/utility/support/evil/pure_evil.cpp
  shared/utility/support/evil/pure_evil.hpp
  shared/utility/vision/Vision.cpp
  shared/utility/vision/Vision.hpp
  shared/utility/vision/fourcc.hpp
Labels: enhancement

#584 Fixes FileExists exception caused by the log file not being a directory
  tools/run.py
Labels: bug

#598 Sets Sensorfilter log level using new construct to NUClear::ERROR
  module/input/SensorFilter/data/config/SensorFilter.yaml
  module/input/SensorFilter/src/SensorFilter.cpp
  module/input/SensorFilter/src/SensorFilter.hpp
Labels: enhancement, high priority, robocup

#600 Makes logging consistent in all modules in `webotsrobocup` role
  module/behaviour/planning/KickPlanner/data/config/KickPlanner.yaml
  module/behaviour/planning/KickPlanner/src/KickPlanner.cpp
  module/behaviour/planning/SimpleWalkPathPlanner/data/config/SimpleWalkPathPlanner.yaml
  module/behaviour/planning/SimpleWalkPathPlanner/src/SimpleWalkPathPlanner.cpp
  module/behaviour/skills/Getup/data/config/Getup.yaml
  module/behaviour/skills/Getup/src/Getup.cpp
  module/behaviour/skills/HeadBehaviourSoccer/data/config/HeadBehaviourSoccer.yaml
  module/behaviour/skills/HeadBehaviourSoccer/src/HeadBehaviourSoccer.cpp
  module/behaviour/skills/KickScript/data/config/KickScript.yaml
  module/behaviour/skills/KickScript/src/KickScript.cpp
  module/behaviour/strategy/SoccerStrategy/data/config/SoccerStrategy.yaml
  module/behaviour/strategy/SoccerStrategy/src/SoccerStrategy.cpp
  module/input/GameController/data/config/GameController.yaml
  module/input/GameController/src/GameController.cpp
  module/localisation/BallLocalisation/data/config/BallLocalisation.yaml
  module/localisation/BallLocalisation/src/BallLocalisation.cpp
  module/motion/HeadController/data/config/HeadController.yaml
  module/motion/HeadController/src/HeadController.cpp
  module/motion/QuinticWalk/data/config/QuinticWalk.yaml
  module/motion/QuinticWalk/data/config/goalie/QuinticWalk.yaml
  module/motion/QuinticWalk/data/config/webots/QuinticWalk.yaml
  module/motion/QuinticWalk/src/QuinticWalk.cpp
  module/network/NUClearNet/data/config/NUClearNet.yaml
  module/network/NUClearNet/src/NUClearNet.cpp
  module/output/ImageCompressor/data/config/ImageCompressor.yaml
  module/output/ImageCompressor/src/ImageCompressor.cpp
  module/output/NetworkForwarder/data/config/NetworkForwarder.yaml
  module/output/NetworkForwarder/src/NetworkForwarder.cpp
  module/platform/Webots/data/config/webots.yaml
  module/platform/Webots/src/Webots.cpp
  module/support/configuration/SoccerConfig/data/config/FieldDescription.yaml
  module/support/configuration/SoccerConfig/src/SoccerConfig.cpp
  module/support/logging/DataLogging/data/config/DataLogging.yaml
  module/support/logging/DataLogging/src/DataLogging.cpp
  module/vision/BallDetector/data/config/BallDetector.yaml
  module/vision/BallDetector/src/BallDetector.cpp
  module/vision/GoalDetector/data/config/GoalDetector.yaml
  module/vision/GoalDetector/src/GoalDetector.cpp
  module/vision/GreenHorizonDetector/data/config/GreenHorizonDetector.yaml
  module/vision/GreenHorizonDetector/src/GreenHorizonDetector.cpp
  module/vision/GreenHorizonDetector/src/GreenHorizonDetector.hpp
  module/vision/VisualMesh/data/config/VisualMesh.yaml
  module/vision/VisualMesh/src/VisualMesh.cpp
Labels: enhancement, high priority, robocup

#605 Tuned penalty kick
  module/motion/ScriptEngine/data/scripts/docker/KickPenalty.yaml
  module/motion/ScriptEngine/data/scripts/webots/KickPenalty.yaml
Labels: enhancement
