Repository NUbots/NUbots, pull requests merged in 2021-08, with the labels that each got.

#312 Added comments to motion messages
  shared/message/motion/GetupCommand.proto
  shared/message/motion/HeadCommand.proto
  shared/message/motion/KickCommand.proto
  shared/message/motion/KinematicsModel.proto
  shared/message/motion/ServoTarget.proto
  shared/message/motion/WalkCommand.proto
Labels: -Documentation, G-Motion, L-Protobuf

#670 Updates KeyboardWalk Macroguard
  module/behaviour/strategy/KeyboardWalk/src/KeyboardWalk.hpp
Labels: L-C++

#671 Purge build volume files rather than re-creating it
  tools/utility/dockerise/run.py
Labels: -Enhancement, G-DevOps-QA, L-Python

#668 Removes a couple of darwin references from KinematicsConfiguration
  module/motion/KinematicsConfiguration/data/config/KinematicsConfiguration.yaml
  module/motion/KinematicsConfiguration/src/KinematicsConfiguration.cpp
  module/motion/KinematicsConfiguration/src/KinematicsConfiguration.hpp
Labels: -Enhancement, G-Motion, L-C++

#311 Added comments to support messages
  module/output/Overview/src/Overview.cpp
  module/support/configuration/SoccerConfig/data/config/FieldDescription.yaml
  module/support/configuration/SoccerConfig/src/SoccerConfig.cpp
  shared/message/support/FieldDescription.proto
  shared/message/support/GlobalConfig.proto
  shared/message/support/SaveConfiguration.proto
  shared/message/support/nuclear/ReactionStatistics.proto
  shared/message/support/nusight/Overview.proto
Labels: -Documentation, G-DevTools, L-Protobuf

#317 Added comments to platform messages
  shared/message/platform/RawSensors.proto
  shared/message/platform/gazebo/Ball.proto
  shared/message/platform/gazebo/Command.proto
  shared/message/platform/gazebo/RawSensors.proto
  shared/message/platform/gazebo/ServoTargets.proto
  shared/message/platform/gazebo/Simulation.proto
  shared/message/platform/gazebo/Torso.proto
Labels: -Documentation, G-Hardware, L-Protobuf

#469 Heaps more clang tidy changes
  module/behaviour/Controller/src/Controller.cpp
  module/behaviour/Controller/src/Controller.hpp
  module/behaviour/planning/KickPlanner/src/KickPlanner.cpp
  module/behaviour/planning/KickPlanner/src/KickPlanner.hpp
  module/behaviour/planning/SimpleWalkPathPlanner/src/SimpleWalkPathPlanner.cpp
  module/behaviour/skills/DirectWalkController/src/DirectWalkController.cpp
  module/behaviour/skills/FallingRelax/src/FallingRelax.cpp
  module/behaviour/skills/FallingRelax/src/FallingRelax.hpp
  module/behaviour/skills/Getup/src/Getup.hpp
  module/behaviour/skills/HeadBehaviourSoccer/src/HeadBehaviourSoccer.cpp
  module/behaviour/skills/HeadBehaviourSoccer/src/HeadBehaviourSoccer.hpp
  module/behaviour/skills/HeadBehaviourSoccer/src/Searcher.hpp
  module/behaviour/skills/KickScript/src/KickScript.cpp
  module/behaviour/skills/KickScript/src/KickScript.hpp
  module/behaviour/skills/Nod/src/Nod.cpp
  module/behaviour/skills/Nod/src/Nod.hpp
  module/behaviour/skills/Stand/src/Stand.cpp
  module/behaviour/strategy/SoccerStrategy/src/SoccerStrategy.cpp
  module/behaviour/strategy/SoccerStrategy/src/SoccerStrategy.hpp
  module/extension/FileWatcher/src/FileWatcher.hpp
  module/motion/QuinticWalk/src/QuinticWalk.hpp
  module/motion/QuinticWalk/src/WalkEngine.cpp
  module/motion/QuinticWalk/src/WalkEngine.hpp
  module/motion/ScriptEngine/src/ScriptEngine.cpp
  module/network/NUClearNet/src/NUClearNet.cpp
  module/platform/darwin/HardwareSimulator/src/HardwareSimulator.cpp
  module/platform/darwin/HardwareSimulator/src/HardwareSimulator.hpp
  module/support/logging/DataPlayback/src/read_packet.hpp
  shared/utility/support/evil/pure_evil.cpp
Labels: -Enhancement, G-DevOps-QA, L-C++

#315 Added comments to vision messages
  shared/message/Geometry.proto
  shared/message/vision/Ball.proto
  shared/message/vision/Goal.proto
  shared/message/vision/GreenHorizon.proto
  shared/message/vision/Obstacle.proto
Labels: -Documentation

#664 Use default constructor for zstr
  docker/Dockerfile
  shared/utility/nbs/Encoder.cpp
  shared/utility/nbs/Encoder.hpp
Labels: -Enhancement, L-C++, D-Not-Too-Hard

#314 Added comments to behaviour messages
  shared/message/behaviour/Behaviour.proto
  shared/message/behaviour/FieldTarget.proto
  shared/message/behaviour/KickPlan.proto
  shared/message/behaviour/MotionCommand.proto
  shared/message/behaviour/ServoCommand.proto
  shared/message/behaviour/SoccerObjectPriority.proto
  shared/message/behaviour/WalkPath.proto
Labels: -Documentation, G-Behaviour, L-Protobuf
