Repository NUbots/NUbots, pull requests merged in 2021-07, with the labels that each got.

#186 Add the DSL and communication components of The Director
  module/extension/Director/CMakeLists.txt
  module/extension/Director/README.md
  module/extension/Director/data/config/Director.yaml
  module/extension/Director/src/Director.cpp
  module/extension/Director/src/Director.hpp
  module/extension/Director/src/director/Provider.hpp
  module/extension/Director/src/director/ProviderGroup.hpp
  module/extension/Director/tests/Director.cpp
  roles/directortest.role
  shared/extension/Behaviour.hpp
  shared/extension/behaviour/commands.hpp
  shared/message/behaviour/state/Stability.proto
Labels: enhancement

#624 Removes GoalSaver
  module/behaviour/skills/GoalSaver/CMakeLists.txt
  module/behaviour/skills/GoalSaver/README.md
  module/behaviour/skills/GoalSaver/data/config/GoalSaver.yaml
  module/behaviour/skills/GoalSaver/src/GoalSaver.cpp
  module/behaviour/skills/GoalSaver/src/GoalSaver.hpp
  module/behaviour/skills/GoalSaver/tests/GoalSaver.cpp
Labels: G-Behaviour, L-C++

#628 Removes WalkPathFollower
  module/behaviour/skills/WalkPathFollower/CMakeLists.txt
  module/behaviour/skills/WalkPathFollower/README.md
  module/behaviour/skills/WalkPathFollower/data/config/WalkPathFollower.yaml
  module/behaviour/skills/WalkPathFollower/src/WalkPathFollower.cpp
  module/behaviour/skills/WalkPathFollower/src/WalkPathFollower.hpp
  module/behaviour/skills/WalkPathFollower/tests/WalkPathFollowerTest.cpp
Labels: G-Behaviour, L-C++

#632 Update accelerometer z axis to positive value
  module/platform/darwin/HardwareSimulator/src/HardwareSimulator.cpp
Labels: !!-Bug, G-DevTools, L-C++

#479 Move compiler warnings settings to target level for modules
  CMakeLists.txt
  cmake/CompilerWarnings.cmake
  module/extension/FileWatcher/tests/FileWatcherTestDirectory.cpp
  module/extension/FileWatcher/tests/FileWatcherTestFile.cpp
  module/platform/darwin/HardwareIO/src/Convert.cpp
  module/platform/darwin/HardwareIO/src/Convert.hpp
  module/platform/darwin/HardwareIO/tests/ConversionTest.cpp
  nuclear/extension/NUClearExtension.cmake
  nuclear/message/Neutron.cmake
  nuclear/module/NUClearModule.cmake
  nuclear/roles/NUClearRole.cmake
  nuclear/utility/NUClearUtility.cmake
  shared/tests/CMakeLists.txt
  shared/tests/utility/math/filter/TestFilters.cpp
  shared/tests/utility/motion/TestKinematics.cpp
  shared/tests/utility/motion/TestSplines.cpp
  shared/utility/math/quaternion.hpp
  shared/utility/motion/splines/Polynom.hpp
Labels: -Enhancement, G-DevOps-QA, L-CMake

#634 Removes gyro stuff from hardware simulator
  module/platform/darwin/HardwareSimulator/src/HardwareSimulator.cpp
  module/platform/darwin/HardwareSimulator/src/HardwareSimulator.hpp
Labels: !!-Bug, G-Hardware, G-Motion, L-C++

#635 Gives Walk Engine logs punctuation for readability
  module/motion/QuinticWalk/src/WalkEngine.cpp
Labels: -Enhancement, G-Motion, L-C++

#637 Refactors vector style messages into vectors
  module/behaviour/skills/Getup/src/Getup.cpp
  module/input/SensorFilter/src/SensorFilter.cpp
  module/platform/Gazebo/src/Gazebo.cpp
  module/platform/Webots/src/Webots.cpp
  module/platform/darwin/HardwareIO/src/HardwareIO.cpp
  module/platform/darwin/HardwareSimulator/data/config/DarwinHardwareSimulator.yaml
  module/platform/darwin/HardwareSimulator/src/HardwareSimulator.cpp
  module/platform/darwin/HardwareSimulator/src/HardwareSimulator.hpp
  shared/message/platform/RawSensors.proto
Labels: -Enhancement, L-C++, L-Protobuf

#639 Adds dependabot config file
  .github/dependabot.yml
Labels: -Dependencies, -New-Feature, G-DevTools

#641 Fixes dependabot config by adding required field
  .github/dependabot.yml
Labels: !!-Bug, G-DevTools, P-NUsight2

#631 Add info to robot selector panel
  .github/dependabot.yml
  nusight2/src/client/components/robot_selector/robot_label/style.css
  nusight2/src/client/components/robot_selector/robot_label/view.tsx
  nusight2/src/client/components/robot_selector/stories/robot_selector.stories.tsx
  nusight2/src/client/components/robot_selector/style.css
Labels: -Enhancement, G-DevTools, L-TypeScript

#638 Fix width of single robot selector
  nusight2/src/client/components/robot_selector_single/style.css
Labels: !!-Bug, G-DevTools, L-TypeScript
