Repository NUbots/NUbots, pull requests merged in 2021-09, with the labels that each got.

#683 Change FileLogHandler to use snake case.
  module/support/logging/FileLogHandler/src/FileLogHandler.cpp
  module/support/logging/FileLogHandler/src/FileLogHandler.hpp
Labels: -Enhancement, D-Good-First-Issue, L-C++

#685 Removes Unused Utilities
  shared/utility/math/geometry/RotatedRectangle.hpp
  shared/utility/strutil/banner.hpp
  shared/utility/support/Limiter.hpp
Labels: G-DevOps-QA, L-C++

#692 Removes unnecessary casts from QuinticWalk reaction
  module/motion/QuinticWalk/src/QuinticWalk.cpp
Labels: -Enhancement, G-DevOps-QA, G-Motion, L-C++

#676 Adds Doxygen documentation generation to the codebase
  .Doxyfile
  .gitignore
  .vscode/settings.json
  docker/Dockerfile
  tools/docs.py
Labels: -Enhancement, -Documentation

#675 Adds error handling code to nusight build script
  nusight2/build_scripts/build.ts
Labels: !!-Bug, L-TypeScript, P-NUsight2, G-DevOps-QA, G-DevTools

#690 Updates Archlinux date and migrates to LLVM12
  docker/Dockerfile
  docker/nugus_sim.Dockerfile
  docker/usr/local/package/intel-graphics-compiler.sh
  shared/utility/nbs/Index.cpp
Labels: -Enhancement, G-DevOps-QA, L-Shell-Script

#640 Adds PR template
  .github/pull_request_template.md
Labels: -New-Feature

#697 Fixes clang build
  CMakeLists.txt
  module/input/SensorFilter/src/MotionModel.hpp
  module/motion/QuinticWalk/src/WalkEngine.hpp
  shared/utility/math/filter/ParticleFilter.hpp
  shared/utility/motion/splines/Polynom.hpp
  shared/utility/motion/splines/SplineContainer.hpp
Labels: !!-Bug, G-DevOps-QA, L-C++

#703 Updates Protobuf version to latest release
  docker/Dockerfile
Labels: -Dependencies, G-DevOps-QA, L-Protobuf

#669 Updates some module READMEs
  module/behaviour/skills/Getup/README.md
  module/behaviour/skills/Stand/README.md
  module/behaviour/strategy/KeyboardWalk/README.md
  module/behaviour/strategy/SoccerStrategy/README.md
  module/behaviour/tools/ScriptRunner/README.md
  module/input/SensorFilter/README.md
  module/motion/ScriptEngine/README.md
Labels: -Enhancement, -Documentation

#667 Updates ScriptTuner README
  module/behaviour/tools/ScriptTuner/README.md
  module/behaviour/tools/ScriptTuner/src/ScriptTuner.cpp
Labels: -Documentation, G-DevTools

#709 NUsight CI fix for missed files when linting in pipeline
  nusight2/build_scripts/build.ts
  nusight2/conf/storybook/webpack.config.ts
  nusight2/package.json
Labels: !!-Bug, L-TypeScript, P-NUsight2, G-DevTools

#711 Rename master->main
  .buildkite/pipeline.yml
  README.md
  doc/ArchInstall/arch-chroot_install.sh
  doc/ArchInstall/arch_install.sh
  doc/PacmanCache/README.md
  doc/PacmanCache/install.sh
  nuclear/README.md
  tools/target.py
Labels: !!-Bug, G-DevOps-QA

#707 Forces CI_BUILD variable off because we aren't ready for Werror/clang-tidy
  .buildkite/pipeline.yml
  CMakeLists.txt
Labels: !!-Bug, G-DevOps-QA, L-CMake

#353 Swap from buildkite to github actions
  .buildkite/NUbots/docker-compose.yml
  .buildkite/NUsight2/plugins/cache/hooks/post-command
  .buildkite/NUsight2/plugins/cache/hooks/pre-command
  .buildkite/NUsight2/plugins/cache/plugin.yml
  .buildkite/pipeline.yml
  .github/dependabot.yml
  .github/workflows/dockerhub-cleanup.yaml
  .github/workflows/format/validate_clang_format.sh
  .github/workflows/format/validate_cmake_format.sh
  .github/workflows/format/validate_python_format.sh
  .github/workflows/images.yaml
  .github/workflows/nubots.yaml
  .github/workflows/nusight.yaml
  README.md
Labels: G-DevOps-QA, -New-Feature

#712 Remove unused functions from RobotModel
  module/localisation/RobotParticleLocalisation/src/RobotModel.hpp
Labels: G-Localisation-Odometry, L-C++

#713 Remove the measurement types that aren't unknown and centre
  shared/message/vision/Goal.proto
Labels: G-Vision

#699 Add game functionality to webots tool
  requirements.txt
  tools/webots.py
Labels: G-DevOps-QA, L-Python, -New-Feature

#701 Changes head IK to use a template function
  module/behaviour/skills/HeadBehaviourSoccer/src/HeadBehaviourSoccer.cpp
  shared/tests/utility/motion/TestKinematics.cpp
  shared/utility/motion/InverseKinematics.cpp
  shared/utility/motion/InverseKinematics.hpp
Labels: -Enhancement, G-Motion, L-C++

#719 Undo incorrect fix
  tools/utility/dockerise/platform.py
Labels: !!-Bug, !!-High-Priority, D-Good-First-Issue, L-Python

#706 Refactors ResampleMethod to prevent invalid configurations
  shared/utility/math/filter/ParticleFilter.hpp
Labels: -Enhancement, G-Localisation-Odometry, L-C++

#691 Modernises Configuration.hpp
  module/input/Camera/src/Camera.cpp
  module/platform/Webots/src/Webots.cpp
  shared/extension/Configuration.hpp
Labels: -Enhancement, G-DevOps-QA, L-C++

#704 Fixes Clang Build (Repeat of #697)
  CMakeLists.txt
  module/input/SensorFilter/src/MotionModel.hpp
  module/motion/QuinticWalk/src/WalkEngine.hpp
  shared/utility/motion/splines/Polynom.hpp
  shared/utility/motion/splines/SplineContainer.hpp
Labels: !!-Bug, G-DevOps-QA, L-C++

#679 Update SimpleWalkPathPlanner into a switch case and functions
  module/behaviour/planning/SimpleWalkPathPlanner/src/SimpleWalkPathPlanner.cpp
  module/behaviour/planning/SimpleWalkPathPlanner/src/SimpleWalkPathPlanner.hpp
Labels: D-Good-First-Issue, G-Behaviour, L-C++

#723 Add clearing of filtered_sensors after each loop
  module/input/SensorFilter/src/SensorFilter.cpp
Labels: G-Localisation-Odometry, L-C++
