Repository NUbots/NUbots, pull requests merged in 2021-12, with the labels that each got.

#765 Move NUsight modules that are used by both client and server into `src/shared`
  nusight2/src/client/components/three/three.tsx
  nusight2/src/client/components/vision/network.ts
  nusight2/src/client/image_decoder/image_decoder.ts
  nusight2/src/server/nuclearnet/web_socket_proxy_nuclearnet_server.ts
  nusight2/src/shared/base/compose.ts
  nusight2/src/shared/base/tests/compose.tests.ts
  nusight2/src/shared/image_decoder/fourcc.ts
  nusight2/src/shared/image_decoder/tests/fourcc.tests.ts
  nusight2/src/virtual_robots/simulators/vision_simulator.ts
Labels: P-NUsight2, G-DevTools

#766 Minor NUsight build fixes
  nusight2/package.json
  nusight2/patches/mobx-react+6.2.2.patch
  nusight2/tsconfig.json
  nusight2/webpack.config.ts
  nusight2/yarn.lock
Labels: P-NUsight2, G-DevTools

#770 Update robocup ecr url and set env vars correctly
  docker/nugus_sim/run.py
  tools/webots.py
Labels: !!-High-Priority, !!-RoboCup

#771 Clang-tidy Automated Changes Again
  module/behaviour/planning/KickPlanner/src/KickPlanner.cpp
  module/input/Camera/src/Camera.cpp
  module/input/SensorFilter/src/SensorFilter.cpp
  module/localisation/BallLocalisation/src/BallLocalisation.cpp
  module/platform/Webots/src/Webots.cpp
  module/platform/darwin/HardwareIO/src/darwin/Darwin.hpp
  shared/extension/Configuration.hpp
  shared/extension/Script.hpp
  shared/extension/behaviour/commands.hpp
  shared/utility/math/geometry/Quad.hpp
  shared/utility/motion/InverseKinematics.hpp
  shared/utility/motion/splines/Combination.hpp
  shared/utility/vision/Vision.hpp
Labels: G-DevOps-QA, L-C++

#772 Updates PR template
  .github/pull_request_template.md
Labels: -Enhancement
