Repository NUbots/NUbots, pull requests merged in 2022-10, with the labels that each got.

#873 Add live Webots odometry error testing
  module/input/SensorFilter/src/SensorFilter.cpp
  module/platform/Webots/src/Webots.cpp
  roles/webots/keyboardwalk.role
  shared/message/platform/RawSensors.proto
  shared/message/platform/webots/messages.proto
Labels: G-Localisation-Odometry, L-C++, -New-Feature

#958 Changes default cmake settings from debug to release
  CMakeLists.txt
Labels: G-DevOps-QA, L-CMake

#961 Clean up HardwareIO
  module/platform/cm740/HardwareIO/src/Convert.hpp
  module/platform/cm740/HardwareIO/src/HardwareIO.cpp
  module/platform/cm740/HardwareIO/src/HardwareIO.hpp
Labels: -Documentation, G-Hardware, L-C++

#935 Remove 'enum' specifier from template declarations which caused warnings
  shared/extension/Behaviour.hpp
Labels: !!-Bug, G-DevOps-QA, L-C++

#964 Allow empty platforms in Configuration extension
  shared/extension/Configuration.hpp
Labels: !!-Bug, L-C++

#953 Fix the extract images nbs tool
  requirements.txt
  tools/nbs/extract_images.py
Labels: !!-Bug, G-Vision, L-Python

#967 Add functionality so Director Providers can Idle
  module/extension/Director/src/director/run_task_pack.cpp
  module/extension/Director/tests/idle.cpp
  shared/extension/Behaviour.hpp
Labels: G-Behaviour, L-C++, -New-Feature

#911 Add configs specific to robocup for the system configurator.
  module/tools/SystemConfiguration/data/config/SystemConfiguration.yaml
  module/tools/SystemConfiguration/data/system/default/etc/systemd/network/40-wlp58s0-robocup.network
  module/tools/SystemConfiguration/data/system/default/etc/wpa_supplicant/wpa_supplicant-wlp58s0.conf
  module/tools/SystemConfiguration/data/system/nugus1/etc/systemd/network/40-wlp58s0-robocup.network
  module/tools/SystemConfiguration/data/system/nugus2/etc/systemd/network/40-wlp58s0-robocup.network
  module/tools/SystemConfiguration/data/system/nugus3/etc/systemd/network/40-wlp58s0-robocup.network
  module/tools/SystemConfiguration/data/system/nugus4/etc/systemd/network/40-wlp58s0-robocup.network
Labels: -Enhancement, G-DevOps-QA

#970 Use a recursive mutex in Director instead of Sync
  module/extension/Director/src/Director.cpp
  module/extension/Director/src/Director.hpp
  module/extension/Director/src/information/get_task_data.cpp
Labels: !!-Bug, G-Behaviour, L-C++

#968 Fix challenge priority function in Director and adds a test that targets the error
  module/extension/Director/src/director/challenge_priority.cpp
  module/extension/Director/tests/challenge_child.cpp
Labels: !!-Bug, G-Behaviour, L-C++

#972 Fix bug where Providers that are no longer active try to run subtasks
  module/extension/Director/src/Director.cpp
  module/extension/Director/src/director/run_task_pack.cpp
Labels: !!-Bug, G-Behaviour, L-C++

#973 Add modules that use the Director to control the servos
  module/motion/Kinematics/CMakeLists.txt
  module/motion/Kinematics/README.md
  module/motion/Kinematics/data/config/Kinematics.yaml
  module/motion/Kinematics/src/Kinematics.cpp
  module/motion/Kinematics/src/Kinematics.hpp
  module/motion/Kinematics/tests/Kinematics.cpp
  module/motion/Servos/CMakeLists.txt
  module/motion/Servos/README.md
  module/motion/Servos/data/config/Servos.yaml
  module/motion/Servos/src/Servos.cpp
  module/motion/Servos/src/Servos.hpp
  module/motion/Servos/tests/Servos.cpp
  roles/test/directormotion.role
  shared/message/behaviour/ServoCommand.proto
  shared/message/motion/Limbs.proto
  shared/message/motion/LimbsIK.proto
  shared/message/motion/ServoCommand.proto
  shared/message/motion/Servos.proto
  shared/utility/motion/ServoLimbMap.hpp
Labels: G-Motion, G-Behaviour, L-C++, L-Protobuf, -New-Feature
