Repository NUbots/NUbots, pull requests merged in 2022-06, with the labels that each got.

#831 Fix out of date sudoers line in arch install script for the robot
  doc/ArchInstall/arch-chroot_install.sh
Labels: !!-Bug, G-DevOps-QA, L-Shell-Script

#832 Remove per robot config for HardwareIO and make the default config use NUgus config
  module/platform/cm740/HardwareIO/data/config/HardwareIO.yaml
  module/platform/cm740/HardwareIO/data/config/nugus1/HardwareIO.yaml
  module/platform/cm740/HardwareIO/data/config/nugus2/HardwareIO.yaml
Labels: !!-Bug

#829 Update Visual Mesh Webots May 2022
  .vscode/settings.json
  module/vision/VisualMesh/data/config/networks/WebotsNetwork.yaml
Labels: -Enhancement, G-Vision

#838 Update camera config files with calibrated values for nugus1.
  module/input/Camera/data/config/nugus1/Cameras/Left.yaml
  module/input/Camera/data/config/nugus1/Cameras/Right.yaml
Labels: G-Vision

#844 Ignore CI builds for things that haven't changed
  .github/dependabot.yaml
  .github/workflows/format/validate_clang_format.sh
  .github/workflows/format/validate_cmake_format.sh
  .github/workflows/format/validate_python_format.sh
  .github/workflows/nubots.yaml
  .github/workflows/nusight.yaml
Labels: -Enhancement, G-DevOps-QA

#845 Stop extra kick in webots_keyboardwalk and add in a kick timeout
  module/behaviour/skills/KickScript/README.md
  module/behaviour/skills/KickScript/data/config/KickScript.yaml
  module/behaviour/skills/KickScript/src/KickScript.cpp
  module/behaviour/skills/KickScript/src/KickScript.hpp
  roles/webots_keyboard.role
Labels: !!-Bug, G-Behaviour, L-C++

#843 Update the Director DSL to solve a premature execution flaw
  module/extension/Director/src/Director.cpp
  module/extension/Director/src/Director.hpp
  module/extension/Director/src/director/challenge_priority.cpp
  module/extension/Director/src/director/remove_task.cpp
  module/extension/Director/src/provider/Provider.hpp
  module/extension/Director/src/provider/ProviderGroup.hpp
  shared/extension/Behaviour.hpp
  shared/extension/behaviour/commands.hpp
Labels: -Enhancement, G-Behaviour, L-C++, D-Harder

#851 Replaces stand up back with rollover/stand up front
  module/behaviour/skills/Getup/src/Getup.cpp
  module/motion/ScriptEngine/data/scripts/nugus/RollOverBack.yaml
  module/motion/ScriptEngine/data/scripts/nugus1/StandUpFront.yaml
Labels: G-Motion, G-Behaviour

#852 Fix NUgus2 standupfront script
  module/motion/ScriptEngine/data/scripts/nugus2/StandUpFront.yaml
Labels: !!-Bug, !!-High-Priority, !!-RoboCup, D-Not-Too-Hard

#850 Stop Configuration running multiple times with the same data during installation phase of the program
  shared/extension/Configuration.hpp
Labels: !!-Bug, G-DevOps-QA, G-Vision, L-C++

#807 Remove mutex from the clock and change the maths
  module/platform/Gazebo/src/Gazebo.cpp
  module/platform/Gazebo/src/Gazebo.hpp
  module/platform/Webots/src/Webots.cpp
  module/platform/Webots/src/Webots.hpp
  shared/clock/clock.cpp
  shared/clock/clock.hpp
Labels: -Enhancement, L-C++

#830 Document Ball Detector
  module/vision/BallDetector/README.md
  module/vision/BallDetector/data/config/BallDetector.yaml
  module/vision/BallDetector/src/BallDetector.cpp
  module/vision/BallDetector/src/BallDetector.hpp
  nusight2/src/client/components/vision/network.ts
  nusight2/src/virtual_robots/simulators/vision_simulator.ts
  shared/message/vision/Ball.proto
Labels: -Documentation, G-Vision, L-C++
