Repository NUbots/NUbots, pull requests merged in 2022-04, with the labels that each got.

#819 Update the codebase to C++20
  CMakeLists.txt
  module/behaviour/tools/ScriptTuner/src/ScriptTuner.cpp
Labels: G-DevOps-QA, L-C++, L-CMake, D-Not-Too-Hard

#821 Remove NUsight Dependabot
  .github/dependabot.yml
Labels: -Dependencies, P-NUsight2, G-DevOps-QA, G-DevTools

#816 Bump zlib and black versions
  doc/Kinematics/Export_Step.py
  docker/Dockerfile
  nuclear/roles/banner/ampscii.py
  report/graph/build_role_graph.py
  report/graph/info/symbol_parser.py
Labels: -Dependencies, G-DevOps-QA, D-Not-Too-Hard
