Repository NUbots/NUbots, pull requests merged in 2022-07, with the labels that each got.

#862 Only include primary source files in Doxygen
  .Doxyfile
Labels: -Enhancement, -Documentation

#870 Make webots and nugus specific image compressor config
  module/output/ImageCompressor/data/config/ImageCompressor.yaml
  module/output/ImageCompressor/data/config/nugus/ImageCompressor.yaml
  module/output/ImageCompressor/data/config/webots/ImageCompressor.yaml
Labels: -Enhancement, !!-High-Priority, !!-RoboCup, G-Vision, D-Not-Too-Hard

#871 Update script tunes june 2022 round two, electric boogaloo
  module/motion/ScriptEngine/data/scripts/nugus1/StandUpFront.yaml
  module/motion/ScriptEngine/data/scripts/nugus2/StandUpFront.yaml
  module/motion/ScriptEngine/data/scripts/nugus3/StandUpFront.yaml
Labels: !!-High-Priority, !!-RoboCup, D-Not-Too-Hard

#875 Update vision to use updated Visual Mesh that has opencl binary caching to reduce install time
  docker/Dockerfile
  module/vision/VisualMesh/data/config/nugus/VisualMesh.yaml
  module/vision/VisualMesh/data/config/webots/VisualMesh.yaml
  module/vision/VisualMesh/src/VisualMesh.cpp
  module/vision/VisualMesh/src/visualmesh/VisualMeshRunner.cpp
  module/vision/VisualMesh/src/visualmesh/VisualMeshRunner.hpp
Labels: -Enhancement, !!-RoboCup, G-Vision, L-C++

#882 Patch intel-compute-runtime to resolve a memory leak
  docker/Dockerfile
  docker/usr/local/package/intel-compute-runtime.sh
Labels: !!-Bug, G-DevOps-QA

#891 Add webots team id and remove darwins
  module/support/configuration/GlobalConfig/data/config/darwin2/GlobalConfig.yaml
  module/support/configuration/GlobalConfig/data/config/darwin3/GlobalConfig.yaml
  module/support/configuration/GlobalConfig/data/config/darwin4/GlobalConfig.yaml
  module/support/configuration/GlobalConfig/data/config/darwin5/GlobalConfig.yaml
  module/support/configuration/GlobalConfig/data/config/darwin6/GlobalConfig.yaml
  module/support/configuration/GlobalConfig/data/config/webots/GlobalConfig.yaml
Labels: RoboCup

#885 Close the event handles in the uv-loop in FileWatcher
  module/extension/FileWatcher/src/FileWatcher.cpp
Labels: !!-Bug, G-DevOps-QA, L-C++

#896 Disable PGP rather than trying to use a separate keychain
  docker/Dockerfile
  docker/Dockerfile.nugus_sim
  docker/etc/pacman.conf
  docker/etc/pacman/pacman.latest.conf
  docker/usr/local/bin/install-package
Labels: G-DevOps-QA
