Repository NUbots/NUbots, pull requests merged in 2022-01, with the labels that each got.

#764 Simplify generated protobuf messages for NUsight
  nusight2/build_scripts/generate_messages.js
Labels: P-NUsight2, G-DevTools

#665 Autocomplete
  nuclear/b.py
  requirements.txt
Labels: L-Python, D-Not-Too-Hard, -New-Feature

#779 Fix random build problems in docker container
  doc/PacmanCache/docker-compose.yml
  docker/Dockerfile
  docker/etc/pacman/pacman.latest.conf
  docker/usr/local/bin/install-package
  docker/usr/local/package/intel-graphics-compiler.sh
Labels: -Dependencies, G-DevOps-QA
