Repository NUbots/NUbots, pull requests merged in 2022-11, with the labels that each got.

#369 Adds coordinate utility unit tests
  shared/tests/data/CoordinateTests.yaml
  shared/tests/data/README.md
  shared/tests/data/cartTestValues.yaml
  shared/tests/utility/math/TestCoordinates.cpp
Labels: -Enhancement, G-DevOps-QA, L-C++

#976 Update module generation for Director and consistency
  tools/module/generate.py
Labels: L-Python

#930 Update the Aravis Camera module to have better robustness and work wi…
  module/input/Camera/src/Camera.cpp
  module/input/Camera/src/Camera.hpp
  module/input/Camera/src/CameraContext.hpp
  module/input/Camera/src/aravis_wrap.hpp
  module/input/Camera/src/description_to_fourcc.hpp
  module/input/Camera/src/settings.hpp
  module/input/Camera/src/time_sync.cpp
  module/input/Camera/src/time_sync.hpp
Labels: L-C++

#916 Add live Webots vision error testing (ball detection)
  module/platform/Webots/src/Webots.cpp
  module/vision/BallDetector/src/BallDetector.cpp
  module/vision/GreenHorizonDetector/src/GreenHorizonDetector.cpp
  module/vision/VisualMesh/src/VisualMesh.cpp
  shared/message/input/Image.proto
  shared/message/platform/webots/messages.proto
  shared/message/vision/GreenHorizon.proto
  shared/message/vision/VisualMesh.proto
Labels: G-Vision, L-C++, -New-Feature
