Repository NUbots/NUbots, pull requests merged in 2023-09, with the labels that each got.

#1225 Improve RawSensors error handling [HW-16]
  module/input/SensorFilter/src/sensorfilter/RawSensors.cpp
  module/platform/HardwareSimulator/src/HardwareSimulator.cpp
  module/platform/OpenCR/HardwareIO/src/HardwareIO.cpp
  module/platform/OpenCR/HardwareIO/src/HardwareIO.hpp
  module/platform/OpenCR/HardwareIO/src/hardwareio/construct_sensors.cpp
  module/platform/OpenCR/HardwareIO/src/hardwareio/process_data.cpp
  shared/message/input/Sensors.proto
  shared/message/platform/RawSensors.proto
  shared/utility/platform/RawSensors.hpp
Labels: !!-Bug, G-Hardware, L-C++

#1230 Tune webots scripts for new kinematics
  shared/utility/skill/scripts/webots/Stand.yaml
  shared/utility/skill/scripts/webots/StandUpBack.yaml
  shared/utility/skill/scripts/webots/StandUpFront.yaml
Labels: G-Motion

#1231 Revert to pre-Director get up detection method
  module/planning/GetUpPlanner/data/config/GetUpPlanner.yaml
  module/planning/GetUpPlanner/src/GetUpPlanner.cpp
  module/planning/GetUpPlanner/src/GetUpPlanner.hpp
Labels: G-Motion, L-C++

#1237 Fix urdf webots model path, specifically for webots docker
  module/actuation/Kinematics/data/config/webots/Kinematics.yaml
  module/input/SensorFilter/data/config/webots/SensorFilter.yaml
  module/platform/Webots/data/config/WebotsCameras/left_camera.yaml
Labels: !!-Bug

#1238 Fixes the nugus sim docker setup
  docker/Dockerfile.nugus_sim
  tools/install.py
Labels: !!-Bug, G-DevOps-QA, L-Python, L-Docker

#1240 Fixes fake/keyboardwalk role for getting started page task
  module/actuation/Kinematics/data/config/Kinematics.yaml
  module/actuation/Kinematics/data/config/nugus/Kinematics.yaml
  module/input/SensorFilter/data/config/SensorFilter.yaml
  module/input/SensorFilter/data/config/nugus/SensorFilter.yaml
  roles/fake/keyboardwalk.role
Labels: !!-Bug

#1246 Fix NetworkForwarder to not think true means 1 FPS
  module/network/NetworkForwarder/src/NetworkForwarder.cpp
  module/network/NetworkForwarder/src/NetworkForwarder.hpp
Labels: !!-Bug, G-DevTools, L-C++

#1239 Update config: Billie's camera, kick distance to ball, turning around
  module/input/Camera/data/config/nugus3/Cameras/Left.yaml
  module/planning/PlanKick/data/config/PlanKick.yaml
  module/planning/PlanWalkPath/data/config/webots/PlanWalkPath.yaml
Labels: Config
