Repository NUbots/NUbots, pull requests merged in 2023-06, with the labels that each got.

#1079 Add OpenCR and DYNAMIXEL Protocol 2.0 compatibility
  CMakeLists.txt
  module/input/SensorFilter/src/sensorfilter/RawSensors.cpp
  module/platform/OpenCR/HardwareIO/CMakeLists.txt
  module/platform/OpenCR/HardwareIO/README.md
  module/platform/OpenCR/HardwareIO/data/config/HardwareIO.yaml
  module/platform/OpenCR/HardwareIO/src/Convert.cpp
  module/platform/OpenCR/HardwareIO/src/Convert.hpp
  module/platform/OpenCR/HardwareIO/src/HardwareIO.cpp
  module/platform/OpenCR/HardwareIO/src/HardwareIO.hpp
  module/platform/OpenCR/HardwareIO/src/NUgus.cpp
  module/platform/OpenCR/HardwareIO/src/NUgus.hpp
  module/platform/OpenCR/HardwareIO/src/dynamixel/v2/Action.hpp
  module/platform/OpenCR/HardwareIO/src/dynamixel/v2/BulkRead.hpp
  module/platform/OpenCR/HardwareIO/src/dynamixel/v2/BulkWrite.hpp
  module/platform/OpenCR/HardwareIO/src/dynamixel/v2/Dynamixel.hpp
  module/platform/OpenCR/HardwareIO/src/dynamixel/v2/DynamixelDevice.hpp
  module/platform/OpenCR/HardwareIO/src/dynamixel/v2/DynamixelServo.hpp
  module/platform/OpenCR/HardwareIO/src/dynamixel/v2/FSR.hpp
  module/platform/OpenCR/HardwareIO/src/dynamixel/v2/FactoryReset.hpp
  module/platform/OpenCR/HardwareIO/src/dynamixel/v2/OpenCR.hpp
  module/platform/OpenCR/HardwareIO/src/dynamixel/v2/Ping.hpp
  module/platform/OpenCR/HardwareIO/src/dynamixel/v2/Read.hpp
  module/platform/OpenCR/HardwareIO/src/dynamixel/v2/Reboot.hpp
  module/platform/OpenCR/HardwareIO/src/dynamixel/v2/RegWrite.hpp
  module/platform/OpenCR/HardwareIO/src/dynamixel/v2/StatusReturn.hpp
  module/platform/OpenCR/HardwareIO/src/dynamixel/v2/SyncRead.hpp
  module/platform/OpenCR/HardwareIO/src/dynamixel/v2/SyncWrite.hpp
  module/platform/OpenCR/HardwareIO/src/dynamixel/v2/Write.hpp
  module/platform/OpenCR/HardwareIO/src/hardwareio/construct_sensors.cpp
  module/platform/OpenCR/HardwareIO/src/hardwareio/handle_response.cpp
  module/platform/OpenCR/HardwareIO/src/hardwareio/packet_queue.cpp
  module/platform/OpenCR/HardwareIO/src/hardwareio/process_data.cpp
  module/platform/OpenCR/HardwareIO/src/hardwareio/send_request.cpp
  module/platform/OpenCR/HardwareIO/src/hardwareio/startup.cpp
  module/platform/OpenCR/HardwareIO/tests/HardwareIO.cpp
  module/platform/cm740/HardwareIO/src/HardwareIO.cpp
  module/platform/cm740/HardwareSimulator/src/HardwareSimulator.cpp
  module/tools/FirmwareInstaller/src/FirmwareInstaller.cpp
  module/tools/FirmwareInstaller/src/FirmwareInstaller.hpp
  roles/directorkeyboardwalk.role
  roles/directorrobocup.role
  roles/keyboardwalk.role
  roles/natnet.role
  roles/ps3walk.role
  roles/robocup.role
  roles/scriptrunner.role
  roles/scripttuner.role
  roles/test/balllocalisation.role
  roles/test/camera.role
  roles/test/gamecontroller.role
  roles/test/headbeh.role
  roles/test/localisation.role
  roles/test/sensor.role
  roles/test/visualmesh.role
  shared/message/platform/RawSensors.proto
  shared/message/platform/ServoLED.proto
  shared/message/platform/StatusReturn.proto
  shared/utility/io/uart.cpp
  shared/utility/io/uart.hpp
  shared/utility/platform/RawSensors.hpp
Labels: !!-High-Priority, G-Hardware, L-C++, L-CMake, L-Protobuf, -New-Feature

#1106 Set hostname to webots if binary name has 'webots' in it
  tools/utility/dockerise/run.py
Labels: !!-Bug, G-DevOps-QA, L-Python

#1100 Apply clang-tidy fixes to ImageCompressor and ImageDecompressor
  module/input/ImageDecompressor/src/ImageDecompressor.cpp
  module/input/ImageDecompressor/src/ImageDecompressor.hpp
  module/input/ImageDecompressor/src/decompressor/Decompressor.hpp
  module/input/ImageDecompressor/src/decompressor/DecompressorFactory.hpp
  module/input/ImageDecompressor/src/decompressor/turbojpeg/Decompressor.cpp
  module/input/ImageDecompressor/src/decompressor/turbojpeg/Decompressor.hpp
  module/input/ImageDecompressor/src/decompressor/turbojpeg/Factory.cpp
  module/input/ImageDecompressor/src/decompressor/turbojpeg/Factory.hpp
  module/output/ImageCompressor/src/ImageCompressor.cpp
  module/output/ImageCompressor/src/ImageCompressor.hpp
  module/output/ImageCompressor/src/compressor/Compressor.hpp
  module/output/ImageCompressor/src/compressor/CompressorFactory.hpp
  module/output/ImageCompressor/src/compressor/turbojpeg/Compressor.cpp
  module/output/ImageCompressor/src/compressor/turbojpeg/Compressor.hpp
  module/output/ImageCompressor/src/compressor/turbojpeg/Factory.cpp
  module/output/ImageCompressor/src/compressor/turbojpeg/Factory.hpp
  module/output/ImageCompressor/src/compressor/vaapi/Compressor.cpp
  module/output/ImageCompressor/src/compressor/vaapi/Compressor.hpp
  module/output/ImageCompressor/src/compressor/vaapi/Factory.cpp
  module/output/ImageCompressor/src/compressor/vaapi/Factory.hpp
  module/output/ImageCompressor/src/compressor/vaapi/cl/make_mosaic_kernel.cpp
  module/output/ImageCompressor/src/compressor/vaapi/cl/opencl_context_for_display.cpp
  module/output/ImageCompressor/src/compressor/vaapi/cl/opencl_error_category.cpp
  module/output/ImageCompressor/src/compressor/vaapi/operation/jpeg_header.cpp
  module/output/ImageCompressor/src/compressor/vaapi/vaapi_error_category.cpp
  module/output/ImageCompressor/src/compressor/vaapi/vaapi_error_category.hpp
Labels: L-C++

#1114 Fix stack overflow in Director where StandStill runs task pack in infinite loop with its dying child
  module/extension/Director/src/director/run_task_pack.cpp
Labels: !!-Bug, G-Behaviour, L-C++

#1115 Add react three fiber
  nusight2/package.json
  nusight2/src/client/components/three/stories/three_fiber.stories.tsx
  nusight2/src/client/components/three/three_fiber.tsx
  nusight2/yarn.lock
Labels: L-TypeScript, P-NUsight2, G-DevTools, -New-Feature

#1118 Fix protobuf on windows
  nusight2/build_scripts/generate_messages.js
Labels: !!-Bug, P-NUsight2

#1124 Add type checking to nusight
  .github/workflows/nusight.yaml
  nusight2/src/client/components/localisation/network.ts
Labels: P-NUsight2, G-DevOps-QA, G-DevTools

#1111 Python requirements update
  tools/requirements.txt
Labels: !!-High-Priority, -Dependencies

#1129 Stop the robot collapsing/moving undesirably on start of program
  module/platform/OpenCR/HardwareIO/README.md
  module/platform/OpenCR/HardwareIO/src/HardwareIO.cpp
  module/platform/OpenCR/HardwareIO/src/HardwareIO.hpp
  module/platform/OpenCR/HardwareIO/src/hardwareio/process_data.cpp
  module/platform/OpenCR/HardwareIO/src/hardwareio/startup.cpp
Labels: !!-Bug, G-Hardware, L-C++

#1140 Move cameras around with nucs
  module/input/Camera/data/config/nugus1/Cameras/Left.yaml
  module/input/Camera/data/config/nugus1/Cameras/Right.yaml
  module/input/Camera/data/config/nugus2/Cameras/Left.yaml
  module/input/Camera/data/config/nugus3/Cameras/Left.yaml
  module/input/Camera/data/config/nugus4/Cameras/Left.yaml
  module/input/Camera/data/config/nugus4/Cameras/Right.yaml
Labels: G-Vision

#1142 Reduce gain on servos
  module/skill/QuinticWalk/data/config/QuinticWalk.yaml
  shared/utility/skill/scripts/nugus/KickLeft.yaml
  shared/utility/skill/scripts/nugus/NodYes.yaml
  shared/utility/skill/scripts/nugus/RelaxHead.yaml
  shared/utility/skill/scripts/nugus/RollOverBack.yaml
  shared/utility/skill/scripts/nugus/RollOverFront.yaml
  shared/utility/skill/scripts/nugus/StandUpBack.yaml
  shared/utility/skill/scripts/nugus/StandUpFront.yaml
  shared/utility/skill/scripts/nugus/Zombie.yaml
  shared/utility/skill/scripts/nugus1/KickLeft.yaml
  shared/utility/skill/scripts/nugus1/KickRight.yaml
Labels: G-Motion

#1141 Add missing modules to robocup
  roles/robocup.role
Labels: G-Behaviour

#1131 Make StandStill and FallingRelaxPlanner run new tasks less frequently
  module/planning/FallingRelaxPlanner/src/FallingRelaxPlanner.cpp
  module/strategy/StandStill/src/StandStill.cpp
  shared/utility/skill/Script.hpp
Labels: -Enhancement, G-Behaviour, L-C++

#1146 Idle the look around when not choosing a new position
  module/planning/PlanLook/src/PlanLook.cpp
Labels: !!-Bug

#1149 Fix rendered visual mesh aspect ratio in NUsight
  nusight2/src/client/components/vision/vision_camera/shaders/visual_mesh.vert
  nusight2/src/client/components/vision/vision_camera/view_model.ts
  nusight2/src/client/components/vision/vision_camera/visual_mesh.ts
Labels: !!-Bug, L-TypeScript, P-NUsight2

#1152 Make the WalkState and Stability messages optional in SensorFilter
  module/input/SensorFilter/src/SensorFilter.cpp
  module/input/SensorFilter/src/SensorFilter.hpp
  module/input/SensorFilter/src/sensorfilter/KalmanFilter.cpp
  module/input/SensorFilter/src/sensorfilter/MahonyFilter.cpp
Labels: !!-Bug, G-Localisation-Odometry, L-C++

#1151 Separate model and packet watchdogs to prevent dropped packets stopping the robot's motions
  module/platform/OpenCR/HardwareIO/src/HardwareIO.cpp
  module/platform/OpenCR/HardwareIO/src/HardwareIO.hpp
  module/platform/OpenCR/HardwareIO/src/hardwareio/startup.cpp
Labels: -Enhancement, G-Hardware, L-C++

#1155 Remove button spoof in OpenCR HardwareIO
  module/platform/OpenCR/HardwareIO/src/HardwareIO.cpp
Labels: G-Hardware

#1159 Add a unit test for Director self intersection and a fix
  module/extension/Director/src/Director.hpp
  module/extension/Director/src/director/find_ok_solution.cpp
  module/extension/Director/src/director/run_task_pack.cpp
  module/extension/Director/tests/self_intersection.cpp
Labels: RoboCup, G-Behaviour, L-C++
