Repository NUbots/NUbots, pull requests merged in 2024-07, with the labels that each got.

#1384 Fix Walk Engine States - Stuck in STOPPING when non-zero command requested before STOPPED
  shared/utility/skill/WalkGenerator.hpp
Labels: !!-Bug, G-Motion, L-C++

#1385 Make FindBall only look if it can't see the ball
  module/strategy/FindObject/data/config/FindObject.yaml
  module/strategy/FindObject/src/FindObject.cpp
  module/strategy/FindObject/src/FindObject.hpp
Labels: G-Behaviour, L-C++

#1386 Update Billies offsets
  module/platform/OpenCR/HardwareIO/data/config/billie/HardwareIO.yaml
Labels: G-Hardware, Config

#1388 Tune Front and Back Getups on Kevin
  shared/utility/skill/scripts/kevin/StandUpBack.yaml
  shared/utility/skill/scripts/kevin/StandUpFront.yaml
Labels: Config

#1395 Tune Billie
  module/input/Camera/data/config/billie/Cameras/Left.yaml
  module/platform/OpenCR/HardwareIO/data/config/billie/HardwareIO.yaml
  module/skill/SplineKick/data/config/SplineKick.yaml
  module/skill/SplineKick/data/config/kevin/SplineKick.yaml
  module/skill/Walk/data/config/Walk.yaml
  module/skill/Walk/data/config/billie/Walk.yaml
  module/skill/Walk/data/config/kevin/Walk.yaml
  shared/utility/skill/scripts/billie/StandUpFront.yaml
  shared/utility/skill/scripts/frankie/StandUpBack.yaml
  shared/utility/skill/scripts/frankie/StandUpFront.yaml
  shared/utility/skill/scripts/kevin/StandUpBack.yaml
  shared/utility/skill/scripts/kevin/StandUpFront.yaml
  shared/utility/skill/scripts/nugus/StandUpBack.yaml
  shared/utility/skill/scripts/nugus/StandUpFront.yaml
Labels: Config

#1401 Franquie tuning
  module/input/Camera/data/config/frankie/Cameras/Left.yaml
  module/platform/OpenCR/HardwareIO/data/config/frankie/HardwareIO.yaml
  module/skill/Walk/data/config/frankie/Walk.yaml
  shared/utility/platform/robot_names.yaml
Labels: G-Hardware, Config

#1407 Make idle stand have a lower priority to find purpose
  module/purpose/Soccer/src/Soccer.cpp
Labels: !!-Bug

#1404 Add logic for whether to approach ball in kickoff
  module/purpose/Striker/data/config/Striker.yaml
  module/purpose/Striker/src/Striker.cpp
  module/purpose/Striker/src/Striker.hpp
Labels: G-Behaviour, L-C++, -New-Feature

#1413 Have bounded box in message of WalkInsideBoundedBox
  module/purpose/Defender/data/config/Defender.yaml
  module/purpose/Defender/data/config/nugus2/Defender.yaml
  module/purpose/Defender/data/config/nugus3/Defender.yaml
  module/purpose/Defender/src/Defender.cpp
  module/purpose/Defender/src/Defender.hpp
  module/strategy/WalkInsideBoundedBox/src/WalkInsideBoundedBox.cpp
  shared/message/strategy/WalkInsideBoundedBox.proto
Labels: G-Behaviour, L-C++

#1406 Dynamically decide robot purposes/soccer positions
  module/network/NetworkForwarder/data/config/NetworkForwarder.yaml
  module/network/RobotCommunication/src/RobotCommunication.cpp
  module/network/RobotCommunication/src/RobotCommunication.hpp
  module/purpose/Soccer/README.md
  module/purpose/Soccer/data/config/Soccer.yaml
  module/purpose/Soccer/data/config/nugus2/Soccer.yaml
  module/purpose/Soccer/data/config/nugus3/Soccer.yaml
  module/purpose/Soccer/data/config/webots/Soccer.yaml
  module/purpose/Soccer/data/config/webots2/Soccer.yaml
  module/purpose/Soccer/data/config/webots3/Soccer.yaml
  module/purpose/Soccer/data/config/webots4/Soccer.yaml
  module/purpose/Soccer/src/Soccer.cpp
  module/purpose/Soccer/src/Soccer.hpp
  module/skill/SplineKick/data/config/SplineKick.yaml
  module/skill/SplineKick/data/config/webots/SplineKick.yaml
  module/support/optimisation/OnboardWalkOptimisation/data/config/OnboardWalkOptimisation.yaml
  nusight2/src/client/components/localisation/fonts/Roboto Medium_Regular.json
  nusight2/src/client/components/localisation/network.ts
  nusight2/src/client/components/localisation/robot_model.ts
  nusight2/src/client/components/localisation/view.tsx
  shared/message/input/Purpose.proto
  shared/message/input/RoboCup.proto
Labels: G-Behaviour, L-C++, -New-Feature

#1415 Billie tune
  module/platform/OpenCR/HardwareIO/data/config/billie/HardwareIO.yaml
  module/skill/Walk/data/config/Walk.yaml
Labels: G-Hardware, Config

#1421 Add UDP filter to robot communication
  module/network/RobotCommunication/data/config/RobotCommunication.yaml
  module/network/RobotCommunication/src/RobotCommunication.cpp
  module/network/RobotCommunication/src/RobotCommunication.hpp
Labels: G-Behaviour, L-C++

#1425 Make buttons work
  module/input/SensorFilter/src/SensorFilter.cpp
Labels: !!-Bug

#1427 Make HardwareIO MainThread'd
  module/platform/OpenCR/HardwareIO/src/HardwareIO.cpp
Labels: !!-Bug

#1426 Remove the ready position from the robocup configuration tool and add dynamic position type
  module/tools/RoboCupConfiguration/src/RoboCupConfiguration.cpp
  module/tools/RoboCupConfiguration/src/RoboCupConfiguration.hpp
Labels: !!-Bug

#1430 Fix conflict with idle and penalisation
  module/purpose/Soccer/src/Soccer.cpp
Labels: !!-Bug, G-Behaviour, L-C++

#1436 Swap sarah and billie nugus hostnames
  shared/utility/platform/robot_names.yaml
Labels: Config

#1438 Add robot ID to NUsight
  module/purpose/Soccer/src/Soccer.cpp
  nusight2/src/client/components/localisation/network.ts
  nusight2/src/client/components/localisation/robot_model.ts
  nusight2/src/client/components/localisation/view.tsx
  shared/message/purpose/Purpose.proto
Labels: L-TypeScript, P-NUsight2, G-DevTools, L-C++, -New-Feature

#1437 Simplify the dynamic purpose function a little
  module/purpose/Soccer/src/Soccer.cpp
Labels: G-Behaviour, L-C++

#1432 Add toggle for robocup fields
  module/network/RobotCommunication/data/config/RobotCommunication.yaml
  module/tools/RoboCupConfiguration/data/config/RoboCupConfiguration.yaml
  module/tools/RoboCupConfiguration/src/RoboCupConfiguration.cpp
  module/tools/RoboCupConfiguration/src/RoboCupConfiguration.hpp
Labels: -Enhancement, L-C++

#1448 Fix VSCode dev container integration
  .devcontainer.json
Labels: Config

#1458 Fix buttons not working when battery voltage is low
  module/platform/OpenCR/HardwareIO/src/hardwareio/construct_sensors.cpp
Labels: !!-Bug, !!-High-Priority, RoboCup
