Repository NUbots/NUbots, pull requests merged in 2025-04, with the labels that each got.

#1546 Update NUsight GitHub Actions workflow to use the Docker image
  .github/workflows/nubots.yaml
  .github/workflows/nusight.yaml
Labels: !!-Bug, G-DevOps-QA

#1544 Update the Dockerfile to November 2024
  CMakeLists.txt
  doc/PacmanCache/docker-compose.yml
  docker/Dockerfile
  docker/etc/pacman.d/mirrorlist
  module/nbs/Player/CMakeLists.txt
  module/nbs/Player/src/generate_emitters.py
  module/network/NetworkForwarder/CMakeLists.txt
  module/network/NetworkForwarder/src/generate_handles.py
  module/platform/OpenCR/HardwareIO/src/Convert.hpp
  module/platform/OpenCR/HardwareIO/src/dynamixel/v2/OpenCR.hpp
  module/purpose/PS3Walk/src/Joystick.hpp
  module/support/logging/DataLogging/CMakeLists.txt
  module/support/logging/DataLogging/src/generate_datalogging.py
  module/support/logging/DataPlayback/CMakeLists.txt
  module/support/logging/DataPlayback/src/generate_dataplayback.py
  module/vision/Yolo/CMakeLists.txt
  module/vision/YoloCoco/CMakeLists.txt
  nuclear/b.py
  nuclear/cmake/Modules/FindPythonLibsNew.cmake
  nuclear/cmake/Modules/GenerateNeutron.cmake
  nuclear/cmake/Scripts/build_message_reflection.py
  nuclear/dependencies.py
  nuclear/message/Neutron.cmake
  nuclear/module/NUClearModule.cmake
  nuclear/roles/NUClearRole.cmake
  shared/utility/input/FrameID.hpp
  shared/utility/input/LimbID.hpp
  shared/utility/input/ServoID.hpp
  shared/utility/support/evil/pure_evil.hpp
  shared/utility/support/yaml_expression.hpp
  tools/utility/dockerise/run.py
Labels: !!-Bug, G-DevOps-QA, L-Python, L-C++, L-CMake, L-Docker

#1532 Director-fy the old Inverse Kinematics Kick (IKKick)
  module/motion/IKKick/src/IKKick.cpp
  module/motion/IKKick/src/IKKickControllers.cpp
  module/skill/IKKick/CMakeLists.txt
  module/skill/IKKick/README.md
  module/skill/IKKick/data/config/IKKick.yaml
  module/skill/IKKick/src/IKKick.cpp
  module/skill/IKKick/src/IKKick.hpp
  module/skill/IKKick/src/IKKickControllers.cpp
  module/skill/IKKick/src/IKKickControllers.hpp
Labels: G-Motion, L-C++

#1548 Fix script tuner play by specifying TIME as the done condition for scripts
  shared/utility/skill/Script.hpp
Labels: !!-Bug, G-Motion, L-C++

#1545 Move servo offsets into the Kinematics Configuration module and give HardwareIO modules unique yaml file names
  module/actuation/KinematicsConfiguration/data/config/Offsets.yaml
  module/actuation/KinematicsConfiguration/data/config/billie/Offsets.yaml
  module/actuation/KinematicsConfiguration/data/config/frankie/Offsets.yaml
  module/actuation/KinematicsConfiguration/data/config/kevin/Offsets.yaml
  module/actuation/KinematicsConfiguration/data/config/sarah/Offsets.yaml
  module/actuation/KinematicsConfiguration/src/KinematicsConfiguration.cpp
  module/platform/NUSense/HardwareIO/data/config/HardwareIO.yaml
  module/platform/NUSense/HardwareIO/data/config/NUSense.yaml
  module/platform/NUSense/HardwareIO/src/HardwareIO.cpp
  module/platform/NUSense/HardwareIO/src/NUgus.hpp
  module/platform/OpenCR/HardwareIO/data/config/HardwareIO.yaml
  module/platform/OpenCR/HardwareIO/data/config/OpenCR.yaml
  module/platform/OpenCR/HardwareIO/data/config/billie/HardwareIO.yaml
  module/platform/OpenCR/HardwareIO/data/config/frankie/HardwareIO.yaml
  module/platform/OpenCR/HardwareIO/data/config/kevin/HardwareIO.yaml
  module/platform/OpenCR/HardwareIO/src/HardwareIO.cpp
  shared/message/actuation/ServoOffsets.proto
Labels: G-Hardware, L-C++, L-Protobuf, Config

#1513 Add unused modules to CI
  .github/workflows/nubots.yaml
  module/platform/NUSense/HardwareIO/CMakeLists.txt
  module/platform/OpenCR/HardwareIO/CMakeLists.txt
  module/support/LocalisationSimulator/src/LocalisationSimulator.cpp
  module/support/Profiler/src/Profiler.cpp
  module/support/ReactionTimer/config/ReactionTimer.yaml
  module/support/ReactionTimer/src/ReactionTimer.cpp
  module/support/logging/FileLogHandler/src/FileLogHandler.cpp
  module/tools/FirmwareInstaller/src/FirmwareInstaller.cpp
  nuclear/module/NUClearModule.cmake
  tools/unused.py
Labels: G-DevOps-QA

#1552 Fix GitHub actions runner out of memory during docker image build
  .github/workflows/images.yaml
  .github/workflows/nubots.yaml
  .github/workflows/nusight.yaml
Labels: !!-Bug, G-DevOps-QA

#1547 Update catch2 version
  docker/Dockerfile
  shared/tests/utility/math/angle.cpp
Labels: G-DevOps-QA, L-C++, L-Docker

#1550 Command line args for setting webots port, player id and team id to facilitate quicker team development
  module/input/GameController/data/config/GameController.yaml
  module/platform/Webots/src/Webots.cpp
  module/support/configuration/GlobalConfig/src/GlobalConfig.cpp
  tools/multi.py
  tools/run.py
  tools/utility/dockerise/run.py
  tools/webots.py
Labels: -Enhancement, G-DevOps-QA, L-Python

#1556 Upgrade b script to support asynchronous execution
  nuclear/b.py
  nuclear/dependencies.py
Labels: L-Python
